version: "3.7"
services:
  frontend:
    container_name: frontend
    build: ./react-pong
    volumes:
      - './react-pong:/usr/src/app'
    ports:
      - 8006:8006
    stdin_open: true
    networks:
      - app
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    container_name: backend
    build: ./nestjs-pong
    volumes:
      - './nestjs-pong:/usr/src/app'
    ports:
      - 3001:3001
      - 3000:3000
    stdin_open: true
    networks:
      - database
      - app
    environment:
      - CHOKIDAR_USEPOLLING=true
  db:
    container_name: database
    image: postgres:13.4-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Transcendence_db
    ports:
      - "5432:5432"
    # volumes:
    #   - ./nestjs-pong:/var/lib/postgresql/data
    networks:
      - database
    restart: always
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - database
    restart: always

networks:
  database:
    driver: bridge
  app:
    driver: bridge
